---
- name: Determine available groups - {{ item.name }}
  ansible.builtin.getent:
    database: group

- name: Set user_groups from item.groups - {{ item.name }}
  ansible.builtin.set_fact:
    user_groups: "{{ item.groups | default([]) }}"

- name: Add 'docker' to user_groups if user is in docker_users - {{ item.name }}
  ansible.builtin.set_fact:
    user_groups: "{{ (user_groups + ['docker']) | unique }}"
  when:
    - "'docker' in ansible_facts.getent_group"
    - docker_users is defined and item.name in docker_users | list

# generate password with:  mkpasswd --method=sha-512
- name: Create/update user with password_hash - {{ item.name }}
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ user_groups }}"
    append: false
    state: present
    shell: /bin/bash
    password: "{{ item.password_hash }}"
    update_password: always
  when: item.password_hash is defined

- name: Create/update user with password - {{ item.name }}
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ user_groups }}"
    append: false
    state: present
    shell: /bin/bash
    password: "{{ item.password | password_hash('sha512', item.password_salt) }}"
    update_password: always
  when: item.password_hash is not defined and item.password is defined and item.password_salt is defined

- name: Add user to sudo - {{ item.name }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ item.name }}
    regexp: "^{{ item.name }} ALL"
    line: "{{ item.name }} ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present
    mode: "0440"
    create: true
    validate: "visudo -cf %s"
  when: item.sudo | default(false) | bool and item.passwordless_sudo is defined and item.passwordless_sudo | bool

- name: Add user to sudo - {{ item.name }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ item.name }}
    regexp: "^{{ item.name }} ALL"
    line: "{{ item.name }} ALL=(ALL:ALL) ALL"
    state: present
    mode: "0440"
    create: true
    validate: "visudo -cf %s"
  when: item.sudo | default(false) | bool and (item.passwordless_sudo is not defined or not (item.passwordless_sudo | bool))

- name: Passwordless sudo - {{ item.name }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ item.name }} ALL"
    line: "{{ item.name }} ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: item.sudo | default(false) | bool and item.passwordless_sudo is defined and item.passwordless_sudo | bool

- name: No passwordless sudo - {{ item.name }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ item.name }} ALL"
    line: "{{ item.name }} ALL=(ALL:ALL) ALL"
    validate: "visudo -cf %s"
  when: item.sudo | default(false) | bool and (item.passwordless_sudo is not defined or not (item.passwordless_sudo | bool))

- name: Remove user from sudoers.d - {{ item.name }}
  ansible.builtin.file:
    path: /etc/sudoers.d/{{ item.name }}
    state: absent
  when: not (item.sudo | default(false) | bool)

- name: Remove passwordless sudo from sudoers - {{ item.name }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ item.name }} ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: not (item.sudo | default(false) | bool)

- name: Remove sudo from sudoers - {{ item.name }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ item.name }} ALL=(ALL:ALL) ALL"
    validate: "visudo -cf %s"
  when: not (item.sudo | default(false) | bool)

- name: Set up authorized keys - {{ item.name }}
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_authorized_keys | join('\n') }}"
    exclusive: true
