---
# .github/workflows/yaml-lint.yml
name: Yamllint GitHub Actions
on:
  push:
  pull_request:
    branches: ["main", "stable", "release/v*"]
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          # yamllint_file_or_dir: '.' # default
          yamllint_config_filepath: .yamllint
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
